### ISSUE TITLE
There is no padding when keyboard activated in text input child of RBSheet 

### ISSUE THREAD

**Issue by Nodirbek3d** [nysamnang/react-native-raw-bottom-sheet#21] opened 2019-07-17 03:49 UTC
consider following code:
```
<KeyboardAvoidingView behavior="padding">
      <RBSheet ref={ref => {
        this.RBSheet = ref;
      }}
      height={450}
      duration={250}
      customStyles={{
          container:{
            zIndex: 9999,
            alignItems: "center",
            // justifyContent: "center" 
          }
        }
      }>
              <TextInput 
                style={[styles.border, {width: "90%", height: 32, borderColor: "white", borderBottomColor: "rgb(224, 224, 224)", borderWidth:1, fontSize: 16, color:"rgb(166,166,166)"}]}
                placeholder="Maximum"
                placeholderTextColor="rgb(166,166,166)"
                keyboardType="number-pad"
                returnKeyType='done'
                />
      </RBSheet>
      </KeyboardAvoidingView>
```
When user taps on text input box, keyboard slides covers up the sheet, it move up too to focus on text input field

**Comment by tumelomakgaka** [comment] 2019-08-08 15:22
@Nodirbek3d , changing the behavior to position makes it work on Android, but unfortunately doesn't work on iOS

If you need iOS too, you can try using this plugin instead and set the KeyboardAvoidingView behavior to position:
https://github.com/yogiwisesa/react-native-custom-bottom-sheet

**Comment by nysamnang** [comment] 2019-10-04 17:14
Duplicate of #30

**Comment by nysamnang** [comment] 2019-10-04 17:15
@Nodirbek3d @tumelomakgaka This issue has already fixed, please download the latest version.

**Closed by nysamnang** 2019-10-04 17:15 UTC
